### ISSUE TITLE
[BUG] No CLKSTS register

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/qemu#24]
CLKSTS in SHIM is not implemented, it always returns 0x0 values.
I guess it should be near that: https://github.com/thesofproject/qemu/blob/sof-stable/include/hw/adsp/shim.h#L46

**Comment by xiulipan** [comment]
@jajanusz Thanks for reporting this. I will check and try to enable this.

Do we already used this bits or we are going to use it? Can you provide more detail that I can try to test with QEMU.

**Comment by jajanusz** [comment]
@lgirdwood Already added it -> https://github.com/thesofproject/qemu/commit/df4e4e1ada90be71c909b3cc232bb2614de15669

@xiulipan Can you update qemu in CI?

**Comment by xiulipan** [comment]
@jajanusz I just tried to build the QEMU with the latest code, but find test on cavs platform failed during the test. Need to debug before update the QEMU code.

@lgirdwood It seems we got some regression again with cavs platforms again.

**Comment by xiulipan** [comment]
@jajanusz @lgirdwood debug and find the issue is caused by shm file change.

```diff
-    { .name = "ipc", .reg_count = 0, .reg = NULL, .ops = &cavs_ipc_v1_5_io_ops,
+    { .name = "ipc-dsp", .reg_count = 0, .reg = NULL, .ops = &cavs_ipc_v1_5_io_ops,
```
create a RP to make the QEMU update smoothly https://github.com/thesofproject/sof/pull/2021
